package com.pfe.webapp.entity;

public enum NotificationType {
    INFO,
    SUCCESS,
    WARNING,
    ERROR,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_COMPLETED,
    PROJECT_CANCELLED,
    ACTIVITY_ASSIGNED,
    ACTIVITY_COMPLETED,
    REPORT_ADDED,
    BREAKDOWN_DECLARED,
    REPAIR_COMPLETED,
    EQUIPMENT_ASSIGNED,
    TEAM_ASSIGNED,
    MISSION_UPDATED,
    SYSTEM,
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_DELETED,
    EVENT_REMINDER,
    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    INCIDENT_DELETED
}